EASY_SCENARIOS = [
    {"scenario_id": 1, "soil_moisture": 25, "rain_coming_tomorrow": True, "budget": 5000, "correct_action": "wait"},
    {"scenario_id": 2, "soil_moisture": 15, "rain_coming_tomorrow": False, "budget": 5000, "correct_action": "irrigate"},
    {"scenario_id": 3, "soil_moisture": 60, "rain_coming_tomorrow": True, "budget": 5000, "correct_action": "wait"},
    {"scenario_id": 4, "soil_moisture": 20, "rain_coming_tomorrow": True, "budget": 200, "correct_action": "wait"},
    {"scenario_id": 5, "soil_moisture": 10, "rain_coming_tomorrow": False, "budget": 5000, "correct_action": "irrigate"},
]

SHOCK_TYPES = {
    "flood": {
        "description": "Unexpected flood warning.",
        "steps_to_respond": 2,
        "correct_actions": ["drain_field", "stop_irrigation"],
        "wrong_actions": ["irrigate", "apply_fertilizer"],
        "penalty_if_ignored": 0.8,
        "reward_if_handled": 0.6,
    },
    "heatwave": {
        "description": "Heatwave detected. Soil moisture dropping 3x faster.",
        "steps_to_respond": 3,
        "correct_actions": ["irrigate", "apply_mulch"],
        "wrong_actions": ["sell_crop", "do_nothing"],
        "penalty_if_ignored": 0.5,
        "reward_if_handled": 0.5,
    },
    "msp_spike": {
        "description": "Government MSP price spike. Valid for 3 days only.",
        "steps_to_respond": 3,
        "correct_actions": ["sell_crop", "check_mandi_price"],
        "wrong_actions": ["do_nothing", "irrigate"],
        "penalty_if_ignored": 0.3,
        "reward_if_handled": 0.7,
    },
    "pest_invasion": {
        "description": "Sudden pest invasion from neighbouring farm.",
        "steps_to_respond": 3,
        "correct_actions": ["apply_pesticide", "check_pest_alert"],
        "wrong_actions": ["sell_crop", "do_nothing"],
        "penalty_if_ignored": 0.9,
        "reward_if_handled": 0.6,
    },
}

MEDIUM_SCENARIOS = [
    {
        "scenario_id": 1,
        "shock_type": "flood",
        "triggered_on_day": 12,
        "crop": "wheat",
        "crop_health_before_shock": 85,
        "budget": 4000,
        "soil_moisture_before": 45,
        "soil_moisture_after_shock": 95,
        "steps_given": 2,
    },
    {
        "scenario_id": 2,
        "shock_type": "heatwave",
        "triggered_on_day": 8,
        "crop": "rice",
        "crop_health_before_shock": 90,
        "budget": 5000,
        "soil_moisture_before": 55,
        "soil_moisture_after_shock": 20,
        "steps_given": 3,
    },
    {
        "scenario_id": 3,
        "shock_type": "msp_spike",
        "triggered_on_day": 20,
        "crop": "wheat",
        "crop_health_before_shock": 80,
        "budget": 3000,
        "current_price": 2000,
        "spike_price": 3200,
        "spike_lasts_days": 3,
        "steps_given": 3,
    },
    {
        "scenario_id": 4,
        "shock_type": "pest_invasion",
        "triggered_on_day": 15,
        "crop": "vegetables",
        "crop_health_before_shock": 75,
        "budget": 2500,
        "pest_spread_rate": "fast",
        "steps_given": 3,
    },
    {
        "scenario_id": 5,
        "shock_type": "heatwave",
        "triggered_on_day": 5,
        "crop": "wheat",
        "crop_health_before_shock": 95,
        "budget": 800,
        "soil_moisture_before": 60,
        "soil_moisture_after_shock": 18,
        "steps_given": 3,
    },
]

HARD_SCENARIOS = [
    {
        "scenario_id": 1,
        "starting_budget": 5000,
        "season_length_days": 30,
        "crop_options": ["wheat", "rice", "vegetables"],
        "weather_pattern": "normal",
        "pest_events": [{"day": 15, "type": "aphids"}],
        "maximum_possible_profit": 8000,
    },
    {
        "scenario_id": 2,
        "starting_budget": 3000,
        "season_length_days": 30,
        "crop_options": ["wheat", "rice", "vegetables"],
        "weather_pattern": "drought",
        "pest_events": [],
        "maximum_possible_profit": 5500,
    },
    {
        "scenario_id": 3,
        "starting_budget": 8000,
        "season_length_days": 30,
        "crop_options": ["wheat", "rice", "vegetables"],
        "weather_pattern": "heavy_rain",
        "pest_events": [
            {"day": 8, "type": "fungus"},
            {"day": 20, "type": "locust"}
        ],
        "maximum_possible_profit": 12000,
    },
    {
        "scenario_id": 4,
        "starting_budget": 2000,
        "season_length_days": 30,
        "crop_options": ["wheat", "rice", "vegetables"],
        "weather_pattern": "normal",
        "pest_events": [{"day": 5, "type": "locust"}],
        "maximum_possible_profit": 4000,
    },
    {
        "scenario_id": 5,
        "starting_budget": 10000,
        "season_length_days": 30,
        "crop_options": ["wheat", "rice", "vegetables"],
        "weather_pattern": "normal",
        "pest_events": [
            {"day": 10, "type": "aphids"},
            {"day": 18, "type": "fungus"},
            {"day": 25, "type": "locust"}
        ],
        "maximum_possible_profit": 18000,
    },
]